package com.alpha.entity;

import java.util.Date;

public class Babel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column babel.id
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column babel.jingwen
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    private String jingwen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column babel.read_time
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    private Date readTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column babel.chapter_count
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    private Integer chapterCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column babel.name
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column babel.id
     *
     * @return the value of babel.id
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column babel.id
     *
     * @param id the value for babel.id
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column babel.jingwen
     *
     * @return the value of babel.jingwen
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public String getJingwen() {
        return jingwen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column babel.jingwen
     *
     * @param jingwen the value for babel.jingwen
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public void setJingwen(String jingwen) {
        this.jingwen = jingwen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column babel.read_time
     *
     * @return the value of babel.read_time
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column babel.read_time
     *
     * @param readTime the value for babel.read_time
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column babel.chapter_count
     *
     * @return the value of babel.chapter_count
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public Integer getChapterCount() {
        return chapterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column babel.chapter_count
     *
     * @param chapterCount the value for babel.chapter_count
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public void setChapterCount(Integer chapterCount) {
        this.chapterCount = chapterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column babel.name
     *
     * @return the value of babel.name
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column babel.name
     *
     * @param name the value for babel.name
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}