spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
    default-property-inclusion: non_empty #不序列化null和""字段
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3306/tq?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: alpha
# tomcat
server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
# mybatis
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    useGeneratedKeys: true
  mapper-locations: classpath:mapper/*.xml
