package com.alpha.mapper;

import com.alpha.entity.Babel;
import com.alpha.entity.BabelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    long countByExample(BabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    int deleteByExample(BabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    int insert(Babel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    int insertSelective(Babel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    List<Babel> selectByExample(BabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    Babel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") Babel record, @Param("example") BabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    int updateByExample(@Param("record") Babel record, @Param("example") BabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    int updateByPrimaryKeySelective(Babel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table babel
     *
     * @mbg.generated Tue Sep 29 13:15:02 CST 2020
     */
    int updateByPrimaryKey(Babel record);
}